import "./style.css";

// import "./_house";
// import "./04-webpack";
// import "./05-transform-objects";
// import "./06-animations";
// import "./07-cameras";
// import "./08-fullscreen-and-resizing";
// import "./09-geometries";
// import "./10-debug-ui";
// import "./11-textures";
// import "./12-materials";
// import "./13-3d-text";
// import "./15-lights";
// import "./16-shadows";
// import "./17-haunted-house";
// import "./18-particles";
// import "./19-galaxy-generator";
// import "./20-raycaster";
// import "./21-scroll-based-animation";
// import "./22-physics";
// import "./23-imported-models";
// import "./24-custom-models-with-blender";
// import "./25-realistic-render";
// import "./26-code-structuring-for-bigger-projects";
// import "./27-shaders";
// import "./28-shader-patterns";
// import "./29-raging-sea";
// import "./30-animated-galaxy";
// import "./31-modified-materials";
import "./32-post-processing";
